// src/lib/supabase/admin.ts
import { createClient } from '@supabase/supabase-js';
import { Database } from '../types/db'; // Will be generated by Supabase CLI

/**
 * Creates a Supabase client using the `service_role` key.
 * This client has full administrative privileges and should ONLY be used
 * in server-side contexts (API Routes, Server Actions) and NEVER exposed to the client.
 * Ideal for sensitive operations like image deletion or calling RPC functions.
 */
export const createAdminClient = () => {
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
    throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY environment variables.');
  }
  return createClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    {
      auth: {
        persistSession: false, // No session needed for admin key
      },
    }
  );
};