"use client";
import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ProductFormValues } from '@/lib/validations/product';
import ProductForm from '@/components/products/ProductForm';
import { toast } from 'react-hot-toast';
import LoadingSpinner from '@/components/common/LoadingSpinner';
import EmptyState from '@/components/common/EmptyState';
import { ProductFormCombined, ProductWithCategory } from '@/lib/types/models';
export default function EditProductPage({ params }: { params: { id: string } }) { const productId = params.id; const router = useRouter(); const [initialData, setInitialData] = useState<ProductFormCombined | null>(null); const [isLoading, setIsLoading] = useState(true); const [isSubmitting, setIsSubmitting] = useState(false); useEffect(() => { fetch(`/api/products/${productId}`).then(async r => { if (!r.ok) throw new Error(); const productData: ProductWithCategory = await r.json(); setInitialData({ ...productData, price: Number(productData.price) }); }).catch(() => toast.error('Failed to load product for editing.')).finally(() => setIsLoading(false)); }, [productId]); const onSubmit = async (data: ProductFormValues) => { setIsSubmitting(true); const formData = new FormData(); formData.append('name', data.name); formData.append('description', data.description || ''); formData.append('price', data.price.toString()); formData.append('category_id', data.category_id || ''); formData.append('active', data.active.toString()); formData.append('existing_image_url', initialData?.image_url || ''); if (data.image_file?.length) formData.append('image_file', data.image_file[0]); else if (!data.image_url && initialData?.image_url) formData.append('remove_image', 'true'); try { const response = await fetch(`/api/products/${productId}`, { method: 'PUT', body: formData }); if (!response.ok) throw new Error((await response.json()).message); toast.success('Product updated successfully!'); router.push('/products'); } catch { toast.error('Failed to update product.'); } finally { setIsSubmitting(false); } }; if (isLoading) return <LoadingSpinner className="min-h-[calc(100vh-120px)]" />; if (!initialData) return <EmptyState title="Product Not Found" message="The beer product you are looking for does not exist." />; return <div className="container mx-auto py-8"><h1 className="text-3xl font-bold text-gray-50 mb-6">EDIT BEER</h1><div className="max-w-xl mx-auto p-6 rounded-lg border border-gray-700 bg-gray-800 shadow-lg"><ProductForm initialData={initialData} onSubmit={onSubmit} isLoading={isSubmitting} /></div></div>; }
